// Indian States/ UT and Districts
const india = {
    0: [
      { "Name": "Srikakulam" },
      { "Name": "Parvathipuram Manyam" },
      { "Name": "Vizianagaram" },
      { "Name": "Visakhapatnam" },
      { "Name": "Alluri Sitharama Raju" },
      { "Name": "Anakapalli" },
      { "Name": "Kakinada" },
      { "Name": "East Godavari" },
      { "Name": "Konaseema" },
      { "Name": "Eluru" },
      { "Name": "West Godavari" },
      { "Name": "Nandamuri Taraka Rama Rao" },
      { "Name": "Krishna" },
      { "Name": "Palnadu" },
      { "Name": "Guntur" },
      { "Name": "Bapatla" },
      { "Name": "Prakasam" },
      { "Name": "Sri Potti Sriramulu Nellore" },
      { "Name": "Kurnool" },
      { "Name": "Nandyal" },
      { "Name": "Anantapur" },
      { "Name": "Sri SathyaYSR" },
      { "Name": "Annamayya" },
      { "Name": "Tirupati" },
      { "Name": "Chittoor" }
    ],
    AR: [
      {"Name": "Anjaw"},
      {"Name": "Changlang"},
      {"Name": "East Kameng"},
      {"Name": "East Siang"},
      {"Name": "Kamle"},
      {"Name": "Kra Daadi"},
      {"Name": "Kurung Kumey"},
      {"Name": "Lepa Rada"},
      {"Name": "Lohit"},
      {"Name": "Longding"},
      {"Name": "Lower Dibang Valley"},
      {"Name": "Lower Siang"},
      {"Name": "Lower Subansiri"},
      {"Name": "Namsai"},
      {"Name": "Pakke-Kessang"},
      {"Name": "Papum Pare"},
      {"Name": "Shi Yomi"},
      {"Name": "Siang"},
      {"Name": "Tawang"},
      {"Name": "Tirap"},
      {"Name": "Upper Dibang Valley"},
      {"Name": "Upper Siang"},
      {"Name": "Upper Subansiri"},
      {"Name": "West Kameng"},
      {"Name": "West Siang"},
      {"Name": "Itanagar City Complex"}
    ],
    
    AS: [
      {"Name": "Bajali"},
      {"Name": "Baksa"},
      {"Name": "Barpeta"},
      {"Name": "Biswanath"},
      {"Name": "Bongaigaon"},
      {"Name": "Cachar"},
      {"Name": "Charaideo"},
      {"Name": "Chirang"},
      {"Name": "Darrang"},
      {"Name": "Dhemaji"},
      {"Name": "Dhubri"},
      {"Name": "Dibrugarh"},
      {"Name": "Dima Hasao"},
      {"Name": "Goalpara"},
      {"Name": "Golaghat"},
      {"Name": "Hailakandi"},
      {"Name": "Hojai"},
      {"Name": "Jorhat"},
      {"Name": "Kamrup"},
      {"Name": "Kamrup Metropolitan"},
      {"Name": "Karbi Anglong"},
      {"Name": "Karimganj"},
      {"Name": "Kokrajhar"},
      {"Name": "Lakhimpur"},
      {"Name": "Majuli"},
      {"Name": "Morigaon"},
      {"Name": "Nagaon"},
      {"Name": "Nalbari"},
      {"Name": "Sivasagar"},
      {"Name": "South Salmara Mankachar"},
      {"Name": "Sonitpur"},
      {"Name": "Tinsukia"},
      {"Name": "Udalguri"},
      {"Name": "West Karbi Anglong"},
      {"Name": "Tamulpur"}
    ]
    ,
    BR: [
      {"Name": "Araria"},
      {"Name": "Arwal"},
      {"Name": "Aurangabad"},
      {"Name": "Banka"},
      {"Name": "Begusarai"},
      {"Name": "Bhagalpur"},
      {"Name": "Bhojpur"},
      {"Name": "Buxar"},
      {"Name": "Darbhanga"},
      {"Name": "East Champaran"},
      {"Name": "Gaya"},
      {"Name": "Gopalganj"},
      {"Name": "Jamui"},
      {"Name": "Jehanabad"},
      {"Name": "Kaimur"},
      {"Name": "Katihar"},
      {"Name": "Khagaria"},
      {"Name": "Kishanganj"},
      {"Name": "Lakhisarai"},
      {"Name": "Madhepura"},
      {"Name": "Madhubani"},
      {"Name": "Munger"},
      {"Name": "Muzaffarpur"},
      {"Name": "Nalanda"},
      {"Name": "Nawada"},
      {"Name": "Patna"},
      {"Name": "Purnia"},
      {"Name": "Rohtas"},
      {"Name": "Saharsa"},
      {"Name": "Samastipur"},
      {"Name": "Saran"},
      {"Name": "Sheikhpura"},
      {"Name": "Sheohar"},
      {"Name": "Sitamarhi"},
      {"Name": "Siwan"},
      {"Name": "Supaul"},
      {"Name": "Vaishali"},
      {"Name": "West Champaran"}
    ]
    ,
    CG: [
      {"Name": "Balod"},
      {"Name": "Baloda Bazar-Bhatapara"},
      {"Name": "Balrampur"},
      {"Name": "Bastar"},
      {"Name": "Bemetara"},
      {"Name": "Bijapur"},
      {"Name": "Bilaspur"},
      {"Name": "Dantewada"},
      {"Name": "Dhamtari"},
      {"Name": "Durg"},
      {"Name": "Gariaband"},
      {"Name": "Gaurella-Pendra-Marwahi"},
      {"Name": "Janjgir-Champa"},
      {"Name": "Jashpur"},
      {"Name": "Kabirdham"},
      {"Name": "Kanker"},
      {"Name": "Kondagaon"},
      {"Name": "Korba"},
      {"Name": "Korea"},
      {"Name": "Mahasamund"},
      {"Name": "Manendragarh-Chirmiri-Bharatpur"},
      {"Name": "Mohla Manpur"},
      {"Name": "Mungeli"},
      {"Name": "Narayanpur"},
      {"Name": "Raigarh"},
      {"Name": "Raipur"},
      {"Name": "Rajnandgaon"},
      {"Name": "Sarangarh-Bilaigarh"},
      {"Name": "Shakti"},
      {"Name": "Sukma"},
      {"Name": "Surajpur"},
      {"Name": "Surguja"},
      {"Name": "Khairagarh-Chhuikhadan-Gandai"}
    ]
    ,
    GA: [
      {"Name": "North Goa"},
      {"Name": "South Goa"}
    ]
    ,
    GJ: [
      {"Name": "Ahmedabad"},
      {"Name": "Amreli"},
      {"Name": "Anand"},
      {"Name": "Aravalli"},
      {"Name": "Banaskantha"},
      {"Name": "Bharuch"},
      {"Name": "Bhavnagar"},
      {"Name": "Botad"},
      {"Name": "Chhota Udaipur"},
      {"Name": "Dahod"},
      {"Name": "Dang"},
      {"Name": "Devbhumi Dwarka"},
      {"Name": "Gandhinagar"},
      {"Name": "Gir Somnath"},
      {"Name": "Jamnagar"},
      {"Name": "Junagadh"},
      {"Name": "Kheda"},
      {"Name": "Kutch"},
      {"Name": "Mahisagar"},
      {"Name": "Mehsana"},
      {"Name": "Morbi"},
      {"Name": "Narmada"},
      {"Name": "Navsari"},
      {"Name": "Panchmahal"},
      {"Name": "Patan"},
      {"Name": "Porbandar"},
      {"Name": "Rajkot"},
      {"Name": "Sabarkantha"},
      {"Name": "Surat"},
      {"Name": "Surendranagar"},
      {"Name": "Tapi"},
      {"Name": "Vadodara"},
      {"Name": "Valsad"}
    ],
    
    HR: [
      {"Name": "Ambala"},
      {"Name": "Bhiwani"},
      {"Name": "Charkhi Dadri"},
      {"Name": "Faridabad"},
      {"Name": "Fatehabad"},
      {"Name": "Gurugram"},
      {"Name": "Hisar"},
      {"Name": "Jhajjar"},
      {"Name": "Jind"},
      {"Name": "Kaithal"},
      {"Name": "Karnal"},
      {"Name": "Kurukshetra"},
      {"Name": "Mahendragarh"},
      {"Name": "Nuh"},
      {"Name": "Palwal"},
      {"Name": "Panchkula"},
      {"Name": "Panipat"},
      {"Name": "Rewari"},
      {"Name": "Rohtak"},
      {"Name": "Sirsa"},
      {"Name": "Sonipat"},
      {"Name": "Yamunanagar"}
    ],
    
    HP: [
      {"Name": "Bilaspur"},
      {"Name": "Chamba"},
      {"Name": "Hamirpur"},
      {"Name": "Kangra"},
      {"Name": "Kinnaur"},
      {"Name": "Kullu"},
      {"Name": "Lahaul and Spiti"},
      {"Name": "Mandi"},
      {"Name": "Shimla"},
      {"Name": "Sirmaur"},
      {"Name": "Solan"},
      {"Name": "Una"}
    ]
    ,
    JH: [
      {"Name": "Bokaro"},
      {"Name": "Chatra"},
      {"Name": "Deoghar"},
      {"Name": "Dhanbad"},
      {"Name": "Dumka"},
      {"Name": "East Singhbhum"},
      {"Name": "Garhwa"},
      {"Name": "Giridih"},
      {"Name": "Godda"},
      {"Name": "Gumla"},
      {"Name": "Hazaribag"},
      {"Name": "Jamtara"},
      {"Name": "Khunti"},
      {"Name": "Koderma"},
      {"Name": "Latehar"},
      {"Name": "Lohardaga"},
      {"Name": "Pakur"},
      {"Name": "Palamu"},
      {"Name": "Ramgarh"},
      {"Name": "Ranchi"},
      {"Name": "Sahibganj"},
      {"Name": "Seraikela-Kharsawan"},
      {"Name": "Simdega"},
      {"Name": "West Singhbhum"}
    ]
    ,
    KA: [
      {"Name": "Bagalkot"},
      {"Name": "Bellary"},
      {"Name": "Belgaum"},
      {"Name": "Bangalore Rural"},
      {"Name": "Bangalore Urban"},
      {"Name": "Bidar"},
      {"Name": "Chamarajanagara"},
      {"Name": "Chikkaballapur"},
      {"Name": "Chikmagalur"},
      {"Name": "Chitradurga"},
      {"Name": "Dakshina Kannada"},
      {"Name": "Davanagere"},
      {"Name": "Dharwad"},
      {"Name": "Gadag"},
      {"Name": "Gulbarga"},
      {"Name": "Hassan"},
      {"Name": "Haveri"},
      {"Name": "Kodagu"},
      {"Name": "Kolar"},
      {"Name": "Koppala"},
      {"Name": "Mandya"},
      {"Name": "Mysore"},
      {"Name": "Raichur"},
      {"Name": "Ramanagara"},
      {"Name": "Shimoga"},
      {"Name": "Tumakuru"},
      {"Name": "Udupi"},
      {"Name": "Uttara Kannada"},
      {"Name": "Vijayanagara"},
      {"Name": "Vijayapura"},
      {"Name": "Yadgir"}
    ]
    ,
    KL: [
      {"Name": "Alappuzha"},
      {"Name": "Ernakulam"},
      {"Name": "Idukki"},
      {"Name": "Kannur"},
      {"Name": "Kasaragod"},
      {"Name": "Kollam"},
      {"Name": "Kottayam"},
      {"Name": "Kozhikode"},
      {"Name": "Malappuram"},
      {"Name": "Palakkad"},
      {"Name": "Pathanamthitta"},
      {"Name": "Thrissur"},
      {"Name": "Thiruvananthapuram"},
      {"Name": "Wayanad"}
    ]
    ,
    MP: [
      {"Name": "Agar Malwa"},
      {"Name": "Alirajpur"},
      {"Name": "Anuppur"},
      {"Name": "Ashoknagar"},
      {"Name": "Balaghat"},
      {"Name": "Barwani"},
      {"Name": "Betul"},
      {"Name": "Bhind"},
      {"Name": "Bhopal"},
      {"Name": "Burhanpur"},
      {"Name": "Chachoda"},
      {"Name": "Chhatarpur"},
      {"Name": "Chhindwara"},
      {"Name": "Damoh"},
      {"Name": "Datia"},
      {"Name": "Dewas"},
      {"Name": "Dhar"},
      {"Name": "Dindori"},
      {"Name": "Guna"},
      {"Name": "Gwalior"},
      {"Name": "Harda"},
      {"Name": "Narmadapuram"},
      {"Name": "Indore"},
      {"Name": "Jabalpur"},
      {"Name": "Jhabua"},
      {"Name": "Katni"},
      {"Name": "Khandwa (East Nimar)"},
      {"Name": "Khargone (West Nimar)"},
      {"Name": "Maihar"},
      {"Name": "Mandla"},
      {"Name": "Mandsaur"},
      {"Name": "Morena"},
      {"Name": "Narsinghpur"},
      {"Name": "Nagda"},
      {"Name": "Neemuch"},
      {"Name": "Niwari"},
      {"Name": "Panna"},
      {"Name": "Raisen"},
      {"Name": "Rajgarh"},
      {"Name": "Ratlam"},
      {"Name": "Rewa"},
      {"Name": "Sagar"},
      {"Name": "Satna"},
      {"Name": "Sehore"},
      {"Name": "Seoni"},
      {"Name": "Shahdol"},
      {"Name": "Shajapur"},
      {"Name": "Sheopur"},
      {"Name": "Shivpuri"},
      {"Name": "Sidhi"},
      {"Name": "Singrauli"},
      {"Name": "Tikamgarh"},
      {"Name": "Ujjain"},
      {"Name": "Umaria"},
      {"Name": "Vidisha"}
    ]
    ,
    MH: [
      {"Name": "Ahmednagar"},
      {"Name": "Akola"},
      {"Name": "Amravati"},
      {"Name": "Aurangabad"},
      {"Name": "Beed"},
      {"Name": "Bhandara"},
      {"Name": "Buldhana"},
      {"Name": "Chandrapur"},
      {"Name": "Dhule"},
      {"Name": "Gadchiroli"},
      {"Name": "Gondia"},
      {"Name": "Hingoli"},
      {"Name": "Jalgaon"},
      {"Name": "Jalna"},
      {"Name": "Kolhapur"},
      {"Name": "Latur"},
      {"Name": "Mumbai City"},
      {"Name": "Mumbai suburban"},
      {"Name": "Nanded"},
      {"Name": "Nandurbar"},
      {"Name": "Nagpur"},
      {"Name": "Nashik"},
      {"Name": "Osmanabad"},
      {"Name": "Palghar"},
      {"Name": "Parbhani"},
      {"Name": "Pune"},
      {"Name": "Raigad"},
      {"Name": "Ratnagiri"},
      {"Name": "Sangli"},
      {"Name": "Satara"},
      {"Name": "Sindhudurg"},
      {"Name": "Solapur"},
      {"Name": "Thane"},
      {"Name": "Wardha"},
      {"Name": "Washim"},
      {"Name": "Yavatmal"}
    ]
    ,
    MN:[
      {"Name": "Bishnupur"},
      {"Name": "Chandel"},
      {"Name": "Churachandpur"},
      {"Name": "Imphal East"},
      {"Name": "Imphal West"},
      {"Name": "Jiribam"},
      {"Name": "Kakching"},
      {"Name": "Kamjong"},
      {"Name": "Kangpokpi"},
      {"Name": "Noney"},
      {"Name": "Pherzawl"},
      {"Name": "Senapati"},
      {"Name": "Tamenglong"},
      {"Name": "Tengnoupal"},
      {"Name": "Thoubal"},
      {"Name": "Ukhrul"}
    ]
    ,
    ML: [
      {"Name": "East Garo Hills"},
      {"Name": "East Khasi Hills"},
      {"Name": "East Jaintia Hills"},
      {"Name": "Eastern West Khasi Hills district"},
      {"Name": "North Garo Hills"},
      {"Name": "Ri Bhoi"},
      {"Name": "South Garo Hills"},
      {"Name": "South West Garo Hills"},
      {"Name": "South West Khasi Hills"},
      {"Name": "West Jaintia Hills"},
      {"Name": "West Garo Hills"},
      {"Name": "West Khasi Hills"}
    ]
    ,
    MZ: [
      {"Name": "Aizawl"},
      {"Name": "Champhai"},
      {"Name": "Hnahthial"},
      {"Name": "Khawzawl"},
      {"Name": "Kolasib"},
      {"Name": "Lawngtlai"},
      {"Name": "Lunglei"},
      {"Name": "Mamit"},
      {"Name": "Saiha"},
      {"Name": "Saitual"},
      {"Name": "Serchhip"}
    ]
    ,
    NL: [
      {"Name": "Chümoukedima"},
      {"Name": "Dimapur"},
      {"Name": "Kiphire"},
      {"Name": "Kohima"},
      {"Name": "Longleng"},
      {"Name": "Mokokchung"},
      {"Name": "Mon"},
      {"Name": "Niuland"},
      {"Name": "Noklak"},
      {"Name": "Peren"},
      {"Name": "Phek"},
      {"Name": "Shamator"},
      {"Name": "Tseminyü"},
      {"Name": "Tuensang"},
      {"Name": "Wokha"},
      {"Name": "Zunheboto"}
    ]
    ,
    OD: [
      {"Name": "Angul"},
      {"Name": "Boudh (Bauda)"},
      {"Name": "Bhadrak"},
      {"Name": "Balangir"},
      {"Name": "Bargarh (Baragarh)"},
      {"Name": "Balasore"},
      {"Name": "Cuttack"},
      {"Name": "Debagarh (Deogarh)"},
      {"Name": "Dhenkanal"},
      {"Name": "Ganjam"},
      {"Name": "Gajapati"},
      {"Name": "Jharsuguda"},
      {"Name": "Jajpur"},
      {"Name": "Jagatsinghpur"},
      {"Name": "Khordha"},
      {"Name": "Kendujhar"},
      {"Name": "Kalahandi"},
      {"Name": "Kandhamal"},
      {"Name": "Koraput"},
      {"Name": "Kendrapara"},
      {"Name": "Malkangiri"},
      {"Name": "Mayurbhanj"},
      {"Name": "Nabarangpur"},
      {"Name": "Nuapada"},
      {"Name": "Nayagarh"},
      {"Name": "Puri"},
      {"Name": "Rayagada"},
      {"Name": "Sambalpur"},
      {"Name": "Subarnapur (Sonepur)"},
      {"Name": "Sundargarh"}
    ],
    PB: [
      {"Name": "Amritsar"},
      {"Name": "Barnala"},
      {"Name": "Bathinda"},
      {"Name": "Firozpur"},
      {"Name": "Faridkot"},
      {"Name": "Fatehgarh Sahib"},
      {"Name": "Fazilka"},
      {"Name": "Gurdaspur"},
      {"Name": "Hoshiarpur"},
      {"Name": "Jalandhar"},
      {"Name": "Kapurthala"},
      {"Name": "Ludhiana"},
      {"Name": "Malerkotla"},
      {"Name": "Mansa"},
      {"Name": "Moga"},
      {"Name": "Sri Muktsar Sahib"},
      {"Name": "Pathankot"},
      {"Name": "Patiala"},
      {"Name": "Rupnagar"},
      {"Name": "Sahibzada Ajit Singh Nagar"},
      {"Name": "Sangrur"},
      {"Name": "Shahid Bhagat Singh Nagar"},
      {"Name": "Tarn Taran"}
    ],
    RJ: [
      {"Name": "Ajmer"},
      {"Name": "Alwar"},
      {"Name": "Bikaner"},
      {"Name": "Barmer"},
      {"Name": "Banswara"},
      {"Name": "Bharatpur"},
      {"Name": "Baran"},
      {"Name": "Bundi"},
      {"Name": "Bhilwara"},
      {"Name": "Churu"},
      {"Name": "Chittorgarh"},
      {"Name": "Dausa"},
      {"Name": "Dholpur"},
      {"Name": "Dungarpur"},
      {"Name": "Sri Ganganagar"},
      {"Name": "Hanumangarh"},
      {"Name": "Jhunjhunu"},
      {"Name": "Jalore"},
      {"Name": "Jodhpur"},
      {"Name": "Jaipur"},
      {"Name": "Jaisalmer"},
      {"Name": "Jhalawar"},
      {"Name": "Karauli"},
      {"Name": "Kota"},
      {"Name": "Nagaur"},
      {"Name": "Pali"},
      {"Name": "Pratapgarh"},
      {"Name": "Rajsamand"},
      {"Name": "Sikar"},
      {"Name": "Sawai Madhopur"},
      {"Name": "Sirohi"},
      {"Name": "Tonk"},
      {"Name": "Udaipur"}
    ],
    SK: [
      {"Name": "East Sikkim"},
      {"Name": "North Sikkim"},
      {"Name": "Pakyong"},
      {"Name": "Soreng"},
      {"Name": "South Sikkim"},
      {"Name": "West Sikkim"}
    ],
    TN: [
      {"Name": "Ariyalur"},
      {"Name": "Chengalpattu"},
      {"Name": "Chennai"},
      {"Name": "Coimbatore"},
      {"Name": "Cuddalore"},
      {"Name": "Dharmapuri"},
      {"Name": "Dindigul"},
      {"Name": "Erode"},
      {"Name": "Kallakurichi"},
      {"Name": "Kanchipuram"},
      {"Name": "Kanyakumari"},
      {"Name": "Karur"},
      {"Name": "Krishnagiri"},
      {"Name": "Madurai"},
      {"Name": "Mayiladuthurai"},
      {"Name": "Nagapattinam"},
      {"Name": "Nilgiris"},
      {"Name": "Namakkal"},
      {"Name": "Perambalur"},
      {"Name": "Pudukkottai"},
      {"Name": "Ramanathapuram"},
      {"Name": "Ranipet"},
      {"Name": "Salem"},
      {"Name": "Sivaganga"},
      {"Name": "Tenkasi"},
      {"Name": "Tiruppur"},
      {"Name": "Tiruchirappalli"},
      {"Name": "Theni"},
      {"Name": "Tirunelveli"},
      {"Name": "Thanjavur"},
      {"Name": "Thoothukudi"},
      {"Name": "Tirupattur"},
      {"Name": "Tiruvallur"},
      {"Name": "Tiruvarur"},
      {"Name": "Tiruvannamalai"},
      {"Name": "Vellore"},
      {"Name": "Viluppuram"},
      {"Name": "Virudhunagar"}
    ],
    TG: [
      {"Name": "Adilabad"},
      {"Name": "Bhadradri Kothagudem"},
      {"Name": "Hanamkonda"},
      {"Name": "Hyderabad"},
      {"Name": "Jagtial"},
      {"Name": "Jangaon"},
      {"Name": "Jayashankar Bhupalpally"},
      {"Name": "Jogulamba Gadwal"},
      {"Name": "Kamareddy"},
      {"Name": "Karimnagar"},
      {"Name": "Khammam"},
      {"Name": "Kumuram Bheem Asifabad"},
      {"Name": "Mahabubabad"},
      {"Name": "Mahbubnagar"},
      {"Name": "Mancherial"},
      {"Name": "Medak"},
      {"Name": "Medchal–Malkajgiri"},
      {"Name": "Mulugu"},
      {"Name": "Nalgonda"},
      {"Name": "Narayanpet"},
      {"Name": "Nagarkurnool"},
      {"Name": "Nirmal"},
      {"Name": "Nizamabad"},
      {"Name": "Peddapalli"},
      {"Name": "Rajanna Sircilla"},
      {"Name": "Ranga Reddy"},
      {"Name": "Sangareddy"},
      {"Name": "Siddipet"},
      {"Name": "Suryapet"},
      {"Name": "Vikarabad"},
      {"Name": "Wanaparthy"},
      {"Name": "Warangal"},
      {"Name": "Yadadri Bhuvanagiri"}
    ],
    TR: [
      {"Name": "Dhalai"},
      {"Name": "Gomati"},
      {"Name": "Khowai"},
      {"Name": "North Tripura"},
      {"Name": "Sepahijala"},
      {"Name": "South Tripura"},
      {"Name": "Unakoti"},
      {"Name": "West Tripura"}
    ],
    UP: [
      {"Name": "Agra"},
      {"Name": "Aligarh"},
      {"Name": "Allahabad"},
      {"Name": "Ambedkar Nagar"},
      {"Name": "Amethi"},
      {"Name": "Amroha"},
      {"Name": "Auraiya"},
      {"Name": "Azamgarh"},
      {"Name": "Bagpat"},
      {"Name": "Bahraich"},
      {"Name": "Ballia"},
      {"Name": "Balrampur"},
      {"Name": "Banda"},
      {"Name": "Barabanki"},
      {"Name": "Bareilly"},
      {"Name": "Basti"},
      {"Name": "Bhadohi"},
      {"Name": "Bijnor"},
      {"Name": "Budaun"},
      {"Name": "Bulandshahr"},
      {"Name": "Chandauli"},
      {"Name": "Chitrakoot"},
      {"Name": "Deoria"},
      {"Name": "Etah"},
      {"Name": "Etawah"},
      {"Name": "Faizabad"},
      {"Name": "Farrukhabad"},
      {"Name": "Fatehpur"},
      {"Name": "Firozabad"},
      {"Name": "Gautam Buddha Nagar"},
      {"Name": "Ghaziabad"},
      {"Name": "Ghazipur"},
      {"Name": "Gonda"},
      {"Name": "Gorakhpur"},
      {"Name": "Hamirpur"},
      {"Name": "Hapur"},
      {"Name": "Hardoi"},
      {"Name": "Hathras"},
      {"Name": "Jalaun"},
      {"Name": "Jaunpur"},
      {"Name": "Jhansi"},
      {"Name": "Kannauj"},
      {"Name": "Kanpur Dehat"},
      {"Name": "Kanpur Nagar"},
      {"Name": "Kasganj"},
      {"Name": "Kaushambi"},
      {"Name": "Kushinagar"},
      {"Name": "Lakhimpur Kheri"},
      {"Name": "Lalitpur"},
      {"Name": "Lucknow"},
      {"Name": "Maharajganj"},
      {"Name": "Mahoba"},
      {"Name": "Mainpuri"},
      {"Name": "Mathura"},
      {"Name": "Mau"},
      {"Name": "Meerut"},
      {"Name": "Mirzapur"},
      {"Name": "Moradabad"},
      {"Name": "Muzaffarnagar"},
      {"Name": "Pilibhit"},
      {"Name": "Pratapgarh"},
      {"Name": "Raebareli"},
      {"Name": "Rampur"},
      {"Name": "Saharanpur"},
      {"Name": "Sambhal"},
      {"Name": "Sant Kabir Nagar"},
      {"Name": "Shahjahanpur"},
      {"Name": "Shamli"},
      {"Name": "Shravasti"},
      {"Name": "Siddharthnagar"},
      {"Name": "Sitapur"},
      {"Name": "Sonbhadra"},
      {"Name": "Sultanpur"},
      {"Name": "Unnao"},
      {"Name": "Varanasi"}
    ]
    ,
    UK: [
      {"Name": "Almora"},
      {"Name": "Bageshwar"},
      {"Name": "Chamoli"},
      {"Name": "Champawat"},
      {"Name": "Dehradun"},
      {"Name": "Didihat"},
      {"Name": "Haridwar"},
      {"Name": "Kotdwar"},
      {"Name": "Nainital"},
      {"Name": "Pauri Garhwal"},
      {"Name": "Pithoragarh"},
      {"Name": "Ranikhet"},
      {"Name": "Rudraprayag"},
      {"Name": "Tehri Garhwal"},
      {"Name": "Udham Singh Nagar"},
      {"Name": "Uttarkashi"},
      {"Name": "Yamunotri"}
    ],
    WB: [
      {"Name": "Alipurduar"},
      {"Name": "Bankura"},
      {"Name": "Paschim Bardhaman"},
      {"Name": "Purba Bardhaman"},
      {"Name": "Birbhum"},
      {"Name": "Cooch Behar"},
      {"Name": "Dakshin Dinajpur"},
      {"Name": "Darjeeling"},
      {"Name": "Hooghly"},
      {"Name": "Howrah"},
      {"Name": "Jalpaiguri"},
      {"Name": "Jhargram"},
      {"Name": "Kalimpong"},
      {"Name": "Kolkata"},
      {"Name": "Maldah"},
      {"Name": "Murshidabad"},
      {"Name": "Nadia"},
      {"Name": "North 24 Parganas"},
      {"Name": "Paschim Medinipur"},
      {"Name": "Purba Medinipur"},
      {"Name": "Purulia"},
      {"Name": "South 24 Parganas"},
      {"Name": "Uttar Dinajpur"}
    ],
    AN: [
      {"Name": "Nicobar"},
      {"Name": "North and Middle Andaman"},
      {"Name": "South Andaman"}
    ]
    ,
    CH: [
      {"Name": "Chandigarh"}
    ],    
    DH: [
      {"Name": "Daman"},
      {"Name": "Diu"},
      {"Name": "Dadra and Nagar Haveli"}
    ]
    ,
    JK: [
      {"Name": "Anantnag"},
      {"Name": "Budgam"},
      {"Name": "Bandipore"},
      {"Name": "Baramulla"},
      {"Name": "Doda"},
      {"Name": "Ganderbal"},
      {"Name": "Jammu"},
      {"Name": "Kathua"},
      {"Name": "Kishtwar"},
      {"Name": "Kulgam"},
      {"Name": "Kupwara"},
      {"Name": "Poonch"},
      {"Name": "Pulwama"},
      {"Name": "Rajouri"},
      {"Name": "Ramban"},
      {"Name": "Reasi"},
      {"Name": "Samba"},
      {"Name": "Shopian"},
      {"Name": "Srinagar"},
      {"Name": "Udhampur"}
    ]
    ,
    LA: [
      {"Name": "Kargil"},
      {"Name": "Leh"}
    ]
    ,
    LD: [
      {"Name": "Lakshadweep"}
    ],
    DL: [
      {"Name": "Central Delhi"},
      {"Name": "East Delhi"},
      {"Name": "New Delhi"},
      {"Name": "North Delhi"},
      {"Name": "North East Delhi"},
      {"Name": "North West Delhi"},
      {"Name": "Shahdara district"},
      {"Name": "South Delhi"},
      {"Name": "South East Delhi"},
      {"Name": "South West Delhi"},
      {"Name": "West Delhi"}
    ],
    PY: [
      {"Name": "Karaikal"},
      {"Name": "Mahé"},
      {"Name": "Puducherry"},
      {"Name": "Yanam"}
    ],
  }
  
  export const indianStates = [
    { "state": "Andhra Pradesh", "code": "AP", "Name": "Andhra Pradesh" },
    { "state": "Arunachal Pradesh", "code": "AR", "Name": "Arunachal Pradesh" },
    { "state": "Assam", "code": "AS", "Name": "Assam" },
    { "state": "Bihar", "code": "BR", "Name": "Bihar" },
    { "state": "Chhattisgarh", "code": "CG", "Name": "Chhattisgarh" },
    { "state": "Goa", "code": "GA", "Name": "Goa" },
    { "state": "Gujarat", "code": "GJ", "Name": "Gujarat" },
    { "state": "Haryana", "code": "HR", "Name": "Haryana" },
    { "state": "Himachal Pradesh", "code": "HP", "Name": "Himachal Pradesh" },
    { "state": "Jharkhand", "code": "JH", "Name": "Jharkhand" },
    { "state": "Karnataka", "code": "KA", "Name": "Karnataka" },
    { "state": "Kerala", "code": "KL", "Name": "Kerala" },
    { "state": "Madhya Pradesh", "code": "MP", "Name": "Madhya Pradesh" },
    { "state": "Maharashtra", "code": "MH", "Name": "Maharashtra" },
    { "state": "Manipur", "code": "MN", "Name": "Manipur" },
    { "state": "Meghalaya", "code": "ML", "Name": "Meghalaya" },
    { "state": "Mizoram", "code": "MZ", "Name": "Mizoram" },
    { "state": "Nagaland", "code": "NL", "Name": "Nagaland" },
    { "state": "Odisha", "code": "OD", "Name": "Odisha" },
    { "state": "Punjab", "code": "PB", "Name": "Punjab" },
    { "state": "Rajasthan", "code": "RJ", "Name": "Rajasthan" },
    { "state": "Sikkim", "code": "SK", "Name": "Sikkim" },
    { "state": "Tamil Nadu", "code": "TN", "Name": "Tamil Nadu" },
    { "state": "Telangana", "code": "TG", "Name": "Telangana" },
    { "state": "Tripura", "code": "TR", "Name": "Tripura" },
    { "state": "Uttar Pradesh", "code": "UP", "Name": "Uttar Pradesh" },
    { "state": "Uttarakhand", "code": "UK", "Name": "Uttarakhand" },
    { "state": "West Bengal", "code": "WB", "Name": "West Bengal" },
    { "state": "Andaman and Nicobar", "code": "AN", "Name": "Andaman and Nicobar" },
    { "state": "Chandigarh", "code": "CH", "Name": "Chandigarh" },
    { "state": "Dadra and Nagar Haveli and Daman and Diu", "code": "DH", "Name": "Dadra and Nagar Haveli and Daman and Diu" },
    { "state": "Jammu and Kashmir", "code": "JK", "Name": "Jammu and Kashmir" },
    { "state": "Ladakh", "code": "LA", "Name": "Ladakh" },
    { "state": "Lakshadweep", "code": "LD", "Name": "Lakshadweep" },
    { "state": "New Delhi", "code": "DL", "Name": "New Delhi" },
    { "state": "Puducherry", "code": "PY", "Name": "Puducherry" }
  ]
  
  
  exports.getIndiaState = () => indianStates
  
  export const getIndiaDistrict = (code: any) => {
    return india[code];
  }