/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pages/addNewHostel`; params?: Router.UnknownInputParams; } | { pathname: `/pages/hostelPage`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/register`; params?: Router.UnknownInputParams; } | { pathname: `/pages/studentProfilePage`; params?: Router.UnknownInputParams; } | { pathname: `/pages/dash/AddStudentsSection`; params?: Router.UnknownInputParams; } | { pathname: `/pages/dash/HostelSection`; params?: Router.UnknownInputParams; } | { pathname: `/pages/dash/OwnerHome`; params?: Router.UnknownInputParams; } | { pathname: `/pages/dash/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/pages/hostelProfile/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/pages/studentProfilePage/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/addNewHostel`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/hostelPage`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/login`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/register`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/studentProfilePage`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/dash/AddStudentsSection`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/dash/HostelSection`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/dash/OwnerHome`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/dash/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/pages/hostelProfile/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/pages/studentProfilePage/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/pages/addNewHostel${`?${string}` | `#${string}` | ''}` | `/pages/hostelPage${`?${string}` | `#${string}` | ''}` | `/pages/login${`?${string}` | `#${string}` | ''}` | `/pages/register${`?${string}` | `#${string}` | ''}` | `/pages/studentProfilePage${`?${string}` | `#${string}` | ''}` | `/pages/dash/AddStudentsSection${`?${string}` | `#${string}` | ''}` | `/pages/dash/HostelSection${`?${string}` | `#${string}` | ''}` | `/pages/dash/OwnerHome${`?${string}` | `#${string}` | ''}` | `/pages/dash/Profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pages/addNewHostel`; params?: Router.UnknownInputParams; } | { pathname: `/pages/hostelPage`; params?: Router.UnknownInputParams; } | { pathname: `/pages/login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/register`; params?: Router.UnknownInputParams; } | { pathname: `/pages/studentProfilePage`; params?: Router.UnknownInputParams; } | { pathname: `/pages/dash/AddStudentsSection`; params?: Router.UnknownInputParams; } | { pathname: `/pages/dash/HostelSection`; params?: Router.UnknownInputParams; } | { pathname: `/pages/dash/OwnerHome`; params?: Router.UnknownInputParams; } | { pathname: `/pages/dash/Profile`; params?: Router.UnknownInputParams; } | `/+not-found` | `/pages/hostelProfile/${Router.SingleRoutePart<T>}` | `/pages/studentProfilePage/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/pages/hostelProfile/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/pages/studentProfilePage/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
